version: '3'
services:
  dynamodb-local:
    build:
      context: ./
      dockerfile: ./Dockerfile_dynamodb
    ports:
      - '8000:8000'
    volumes:
      - .:/var/opt/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VOLUME=$PWD
    networks:
      - net

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net

  go-bench:
    build:
      context: ./
      dockerfile: ./Dockerfile_go
    volumes:
      - .:/go/src/dynamodb-benchmark/
    depends_on:
      - dynamodb-local
      - localstack
    environment:
      - DYNAMOLOCAL=http://dynamodb-local:8000
      - LOCALSTACK=http://localstack:4569
    networks:
      - net

networks:
  net:
    driver: bridge
